version: '3.4'

services:
  angularwithnodejs:
    image: angularwithnodejs
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
